import type { Metadata } from 'next';
import {
	Geist_Mono,
	El_Messiri,
	Proza_Libre,
} from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header';

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

const elMessiri = El_Messiri({
	variable: '--font-el-messiri',
	subsets: ['latin'],
});

const prozaLibre = Proza_Libre({
	variable: '--font-proza-libre',
	weight: ['400', '500', '600', '700', '800'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistMono.variable} ${elMessiri.variable} ${prozaLibre.variable} antialiased font-sans bg-star-dust-950 text-star-dust-400`}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
